name: 'Terraform'

on: [push, pull_request]

jobs:
  plan:
    name: 'Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Steup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

  apply:
    name: 'Apply'
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: prod-env

    steps:
    - name: Terraform apply
      run: terraform apply -auto-approve
